project_id = "sffkcqclfiffnpxorodd"

[functions.invite-user]
verify_jwt = false

[functions.notify-deviation-assignment]
verify_jwt = true

[functions.check-deviation-deadlines]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true
