project_id = "sffkcqclfiffnpxorodd"

[functions.invite-user]
verify_jwt = true

[functions.invite-ue-access]
verify_jwt = true

[functions.notify-deviation-assignment]
verify_jwt = true

[functions.check-deviation-deadlines]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.bulk-create-users]
verify_jwt = true

[functions.check-course-expiry]
verify_jwt = false

[functions.create-company-admin]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.check-hms-card-expiry]
verify_jwt = false

[functions.send-test-notification]
verify_jwt = true

[functions.hms-chat]
verify_jwt = true

[functions.generate-ik-mat-content]
verify_jwt = true

[functions.ik-mat-chat]
verify_jwt = true

[functions.ik-hms-chat]
verify_jwt = true

[functions.check-ks2-deadlines]
verify_jwt = false

[functions.parse-sds-pdf]
verify_jwt = true

[functions.send-module-order-confirmation]
verify_jwt = true

[functions.send-document-email]
verify_jwt = true

[functions.send-meeting-minutes]
verify_jwt = true

[functions.sync-employees]
verify_jwt = false

[functions.sync-to-kurs]
verify_jwt = false

[functions.send-bulk-welcome-emails]
verify_jwt = true

[functions.send-welcome-email]
verify_jwt = false

[functions.parse-customer-pdf]
verify_jwt = true

[functions.notify-new-company]
verify_jwt = true

[functions.send-single-welcome-email]
verify_jwt = true

[functions.send-renewal-email]
verify_jwt = true

[functions.create-user-direct]
verify_jwt = true

[functions.notify-time-off-request]
verify_jwt = true

[functions.notify-time-off-approval]
verify_jwt = true

[functions.notify-work-schedule]
verify_jwt = true
