import { useState, useEffect, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import type { Database } from "@/integrations/supabase/types";
import { 
  safeString, 
  safeStringOrNull, 
  safeCategory, 
  safePriority, 
  safeStatus,
  safeTimeFormat,
  safeDateFormat,
  safeBoolean 
} from "@/utils/deviationSanitizer";
import type { DeviationStatus } from "@/utils/deviationSanitizer";

// Valid database category values
export type DeviationCategory = "quality" | "safety" | "environment" | "documentation" | "other" | "process" | "equipment" | "personnel" | "temperature" | "cleaning" | "pest_control" | "allergen" | "traceability" | "hygiene" | "storage" | "pests" | "expiry" | "contamination" | "receiving" | "other_food";

// Re-export for consumers
export type { DeviationStatus };

export interface Deviation {
  id: string;
  deviation_number: string;
  title: string;
  description: string | null;
  category: DeviationCategory;
  priority: "low" | "medium" | "high" | "critical";
  status: DeviationStatus;
  assignee_id: string | null;
  assignee_name: string | null;
  reporter_id: string | null;
  reporter_name: string;
  due_date: string;
  created_at: string;
  updated_at: string;
  // Extended RUH fields
  type?: string;
  incident_location?: string | null;
  incident_time?: string | null;
  incident_type?: string | null;
  severity?: string | null;
  consequences?: string | null;
  involved_persons?: string | null;
  immediate_actions?: string | null;
  preventive_measures?: string | null;
  root_cause_analysis?: string | null;
  reporter_contact?: string | null;
  responsible_receiver?: string | null;
  additional_info?: string | null;
  notify_arbeidstilsynet?: boolean | null;
  notify_insurance?: boolean | null;
  department_id?: string | null;
}

export interface NewDeviationInput {
  title: string;
  description: string;
  category: DeviationCategory;
  type?: string;
  priority: "low" | "medium" | "high" | "critical";
  assignee_id?: string | null;
  assignee_name: string | null;
  due_date: string;
  // Extended fields
  incident_location?: string;
  incident_date?: string | Date;
  incident_time?: string;
  incident_type?: string;
  severity?: string;
  reporter_contact?: string;
  additional_info?: string;
  consequences?: string;
  involved_persons?: string;
  immediate_actions?: string;
  preventive_measures?: string;
  responsible_receiver?: string;
  notify_arbeidstilsynet?: boolean;
  notify_insurance?: boolean;
}

// DB Insert type — deviation_number is generated by trigger, so we omit it
type DeviationInsert = Omit<
  Database["public"]["Tables"]["deviations"]["Insert"],
  "deviation_number"
>;

// DB Update type from generated types
type DeviationUpdate = Database["public"]["Tables"]["deviations"]["Update"];

/**
 * Sanitize status values coming from DB reads.
 * DB may contain legacy values like "in_progress" — normalize to canonical.
 */
function normalizeDeviationRow(row: Record<string, unknown>): Deviation {
  return {
    ...row,
    status: safeStatus(row.status),
    category: safeCategory(row.category),
    priority: safePriority(row.priority),
  } as Deviation;
}

export function useDeviations() {
  const { profile } = useAuth();
  const { toast } = useToast();
  const [deviations, setDeviations] = useState<Deviation[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  const companyId = profile?.company_id;
  const departmentId = profile?.primary_department_id;

  // Fetch deviations
  const fetchDeviations = useCallback(async () => {
    if (!companyId) {
      setIsLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from("deviations")
        .select("*")
        .eq("company_id", companyId)
        .order("created_at", { ascending: false });

      if (error) throw error;
      setDeviations(
        (data || []).map((row) => normalizeDeviationRow(row as Record<string, unknown>))
      );
    } catch (error) {
      console.error("Error fetching deviations:", error);
      toast({
        title: "Feil ved henting",
        description: "Kunne ikke hente avvik. Prøv igjen.",
        variant: "destructive",
      });
    } finally {
      setIsLoading(false);
    }
  }, [companyId, toast]);

  useEffect(() => {
    fetchDeviations();
  }, [fetchDeviations]);

  // Create deviation with sanitized data — no `as any`
  const createDeviation = useCallback(async (input: NewDeviationInput): Promise<Deviation | null> => {
    if (!companyId || !profile) return null;

    setIsSaving(true);
    try {
      const reporterName = [profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.email || "Ukjent";

      // Build insert payload matching DB schema (deviation_number omitted — trigger generates it)
      const insertData: DeviationInsert = {
        company_id: companyId,
        title: safeString(input.title, 'Uten tittel'),
        description: safeStringOrNull(input.description),
        category: safeCategory(input.category),
        priority: safePriority(input.priority),
        status: "open" as string,
        assignee_id: safeStringOrNull(input.assignee_id),
        assignee_name: safeStringOrNull(input.assignee_name),
        reporter_id: profile.id,
        reporter_name: reporterName,
        due_date: input.due_date,
        incident_location: safeStringOrNull(input.incident_location),
        incident_date: safeDateFormat(input.incident_date),
        incident_time: safeTimeFormat(input.incident_time),
        incident_type: safeStringOrNull(input.incident_type),
        severity: safeStringOrNull(input.severity),
        reporter_contact: safeStringOrNull(input.reporter_contact),
        additional_info: safeStringOrNull(input.additional_info),
        consequences: safeStringOrNull(input.consequences),
        involved_persons: safeStringOrNull(input.involved_persons),
        immediate_actions: safeStringOrNull(input.immediate_actions),
        preventive_measures: safeStringOrNull(input.preventive_measures),
        responsible_receiver: safeStringOrNull(input.responsible_receiver),
        notify_arbeidstilsynet: safeBoolean(input.notify_arbeidstilsynet),
        notify_insurance: safeBoolean(input.notify_insurance),
        department_id: departmentId || null,
        ...(input.type ? { type: input.type } : {}),
      };

      const { data, error } = await supabase
        .from("deviations")
        .insert(insertData as Database["public"]["Tables"]["deviations"]["Insert"])
        .select()
        .single();

      if (error) throw error;

      const result = normalizeDeviationRow(data as Record<string, unknown>);
      await fetchDeviations();
      toast({
        title: "Avvik registrert",
        description: `${result.deviation_number}: ${result.title}`,
      });
      return result;
    } catch (error) {
      console.error("Error creating deviation:", error);
      toast({
        title: "Feil ved lagring",
        description: "Kunne ikke registrere avvik. Prøv igjen.",
        variant: "destructive",
      });
      return null;
    } finally {
      setIsSaving(false);
    }
  }, [companyId, profile, departmentId, fetchDeviations, toast]);

  // Update deviation — sanitizes status before writing
  const updateDeviation = useCallback(async (
    id: string, 
    updates: Partial<Pick<Deviation, 
      "status" | "assignee_id" | "assignee_name" | "priority" | 
      "immediate_actions" | "root_cause_analysis" | "preventive_measures" |
      "title" | "description" | "category" | "due_date"
    >>,
    options?: { sendNotification?: boolean; assigneeEmail?: string }
  ): Promise<boolean> => {
    setIsSaving(true);
    try {
      // Sanitize status if present to ensure canonical value hits DB
      const sanitizedUpdates: DeviationUpdate = { ...updates };
      if (updates.status !== undefined) {
        sanitizedUpdates.status = safeStatus(updates.status);
      }
      if (updates.priority !== undefined) {
        sanitizedUpdates.priority = safePriority(updates.priority);
      }
      if (updates.category !== undefined) {
        sanitizedUpdates.category = safeCategory(updates.category);
      }

      const { error } = await supabase
        .from("deviations")
        .update(sanitizedUpdates)
        .eq("id", id);

      if (error) throw error;

      // Update local state with sanitized values
      const updatedDeviation = deviations.find(d => d.id === id);
      setDeviations(prev => prev.map(d => 
        d.id === id ? { ...d, ...sanitizedUpdates } as Deviation : d
      ));

      // Send email notification if assignee changed and email provided
      if (options?.sendNotification && options?.assigneeEmail && updates.assignee_name && updatedDeviation) {
        const assignerName = profile 
          ? [profile.first_name, profile.last_name].filter(Boolean).join(" ") || profile.email || "En bruker"
          : "En bruker";

        try {
          await supabase.functions.invoke("notify-deviation-assignment", {
            body: {
              deviation_id: id,
              deviation_number: updatedDeviation.deviation_number,
              deviation_title: updatedDeviation.title,
              assignee_email: options.assigneeEmail,
              assignee_name: updates.assignee_name,
              assigner_name: assignerName,
              due_date: updatedDeviation.due_date,
              priority: updatedDeviation.priority,
              category: updatedDeviation.category,
            },
          });
        } catch (emailError) {
          console.error("Failed to send email notification:", emailError);
        }
      }

      return true;
    } catch (error) {
      console.error("Error updating deviation:", error);
      toast({
        title: "Feil ved oppdatering",
        description: "Kunne ikke oppdatere avvik. Prøv igjen.",
        variant: "destructive",
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  }, [deviations, profile, toast]);

  // Delete deviation
  const deleteDeviation = useCallback(async (id: string): Promise<boolean> => {
    setIsSaving(true);
    try {
      const { error } = await supabase
        .from("deviations")
        .delete()
        .eq("id", id);

      if (error) throw error;

      setDeviations(prev => prev.filter(d => d.id !== id));
      toast({
        title: "Avvik slettet",
        description: "Avviket ble slettet.",
      });
      return true;
    } catch (error) {
      console.error("Error deleting deviation:", error);
      toast({
        title: "Feil ved sletting",
        description: "Kunne ikke slette avvik. Prøv igjen.",
        variant: "destructive",
      });
      return false;
    } finally {
      setIsSaving(false);
    }
  }, [toast]);

  return {
    deviations,
    isLoading,
    isSaving,
    createDeviation,
    updateDeviation,
    deleteDeviation,
    refetch: fetchDeviations,
  };
}
