import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";
import type { Json } from "@/integrations/supabase/types";

export interface Finding {
  id: string;
  description: string;
  location?: string;
  severity?: "low" | "medium" | "high";
  status: "open" | "closed";
  responsible?: string;
  deadline?: string;
  closedDate?: string;
  escalate_to_avvik?: boolean;
  created_at?: string;
}

export interface CheckpointResponse {
  checkpoint_id: string;
  status: "ok" | "avvik" | "na" | null;
  comment: string;
}

export interface KsModule2Vernerunde {
  id: string;
  project_id: string;
  company_id: string;
  vernerunde_number: string;
  title: string;
  scheduled_date: string;
  completed_date: string | null;
  responsible_name: string;
  responsible_id: string | null;
  participants: string[] | null;
  status: string;
  findings: Finding[];
  notes: string | null;
  completed_by_name: string | null;
  completed_by_id: string | null;
  signature_data: string | null;
  template_id: string | null;
  checklist_responses: CheckpointResponse[];
  created_at: string;
  updated_at: string;
}

export interface CreateVernerundeInput {
  project_id: string;
  title: string;
  scheduled_date: string;
  responsible_name: string;
  responsible_id?: string;
  participants?: string[];
  notes?: string;
}

export function useKsModule2Vernerunder(projectId: string | undefined) {
  const { profile } = useAuth();
  const queryClient = useQueryClient();

  const { data: vernerunder = [], isLoading, refetch } = useQuery({
    queryKey: ["ks-module2-vernerunder", projectId],
    queryFn: async () => {
      if (!projectId) return [];
      
      const { data, error } = await supabase
        .from("ks_module2_vernerunder")
        .select("*")
        .eq("project_id", projectId)
        .order("scheduled_date", { ascending: false });

      if (error) throw error;
      
      return (data || []).map(item => ({
        ...item,
        findings: Array.isArray(item.findings) ? item.findings as unknown as Finding[] : [],
        checklist_responses: Array.isArray(item.checklist_responses) ? item.checklist_responses as unknown as CheckpointResponse[] : [],
      })) as KsModule2Vernerunde[];
    },
    enabled: !!projectId,
  });

  const createVernerunde = useMutation({
    mutationFn: async (input: CreateVernerundeInput) => {
      if (!profile?.company_id) throw new Error("Ingen bedrift funnet");

      // Number is generated by DB trigger to avoid race conditions when
      // two users create vernerunder simultaneously.
      const { data, error } = await supabase
        .from("ks_module2_vernerunder")
        .insert({
          ...input,
          company_id: profile.company_id,
          vernerunde_number: "",
          status: "planned",
          findings: [],
        })
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ks-module2-vernerunder", projectId] });
      toast.success("Vernerunde planlagt");
    },
    onError: (error) => {
      console.error("Error creating vernerunde:", error);
      toast.error("Kunne ikke opprette vernerunde");
    },
  });

  const updateVernerunde = useMutation({
    mutationFn: async ({ id, ...updates }: Partial<KsModule2Vernerunde> & { id: string }) => {
      const { findings: findingsUpdate, checklist_responses: checklistUpdate, ...restUpdates } = updates;
      
      // Build update payload with proper JSON serialization
      const updatePayload: Record<string, unknown> = { ...restUpdates };
      if (findingsUpdate) {
        updatePayload.findings = JSON.parse(JSON.stringify(findingsUpdate)) as Json;
      }
      if (checklistUpdate) {
        updatePayload.checklist_responses = JSON.parse(JSON.stringify(checklistUpdate)) as Json;
      }
      
      const { data, error } = await supabase
        .from("ks_module2_vernerunder")
        .update(updatePayload as any)
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ks-module2-vernerunder", projectId] });
      toast.success("Vernerunde oppdatert");
    },
    onError: (error) => {
      console.error("Error updating vernerunde:", error);
      toast.error("Kunne ikke oppdatere vernerunde");
    },
  });

  const deleteVernerunde = useMutation({
    mutationFn: async (id: string) => {
      const { error } = await supabase
        .from("ks_module2_vernerunder")
        .delete()
        .eq("id", id);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ks-module2-vernerunder", projectId] });
      toast.success("Vernerunde slettet");
    },
    onError: (error) => {
      console.error("Error deleting vernerunde:", error);
      toast.error("Kunne ikke slette vernerunde");
    },
  });

  const completeVernerunde = useMutation({
    mutationFn: async ({ id, findings, signature_data }: { id: string; findings?: Finding[]; signature_data?: string }) => {
      const fullName = profile ? `${profile.first_name || ''} ${profile.last_name || ''}`.trim() : undefined;
      
      const { data, error } = await supabase
        .from("ks_module2_vernerunder")
        .update({
          status: "completed",
          completed_date: new Date().toISOString().split('T')[0],
          completed_by_name: fullName,
          completed_by_id: profile?.id,
          findings: JSON.parse(JSON.stringify(findings || [])) as Json,
          signature_data,
        })
        .eq("id", id)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["ks-module2-vernerunder", projectId] });
      toast.success("Vernerunde fullført");
    },
    onError: (error) => {
      console.error("Error completing vernerunde:", error);
      toast.error("Kunne ikke fullføre vernerunde");
    },
  });

  return {
    vernerunder,
    isLoading,
    refetch,
    createVernerunde,
    updateVernerunde,
    deleteVernerunde,
    completeVernerunde,
  };
}
