import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export interface TravelExpenseReport {
  id: string;
  user_id: string;
  company_id: string;
  report_number: string;
  purpose: string;
  destination: string;
  departure_date: string;
  return_date: string;
  departure_location: string;
  total_km: number;
  mileage_rate: number;
  mileage_amount: number;
  passenger_supplement: number;
  diet_days: number;
  diet_rate: number;
  diet_amount: number;
  accommodation_days: number;
  accommodation_rate: number;
  accommodation_amount: number;
  other_expenses_total: number;
  total_amount: number;
  linked_trip_ids: string[];
  status: string;
  submitted_at: string | null;
  approved_by_id: string | null;
  approved_by_name: string | null;
  approved_at: string | null;
  rejection_reason: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface TravelExpenseItem {
  id: string;
  report_id: string;
  category: string;
  description: string;
  date: string;
  amount: number;
  receipt_path: string | null;
  created_at: string;
}

export interface CreateTravelExpenseInput {
  purpose: string;
  destination: string;
  departure_date: string;
  return_date: string;
  departure_location: string;
  total_km: number;
  mileage_rate: number;
  passenger_supplement?: number;
  diet_days?: number;
  diet_rate?: number;
  accommodation_days?: number;
  accommodation_rate?: number;
  linked_trip_ids?: string[];
  notes?: string;
  items?: {
    category: string;
    description: string;
    date: string;
    amount: number;
    receipt_file?: File;
  }[];
}

export function useTravelExpenseReports() {
  const { profile } = useAuth();
  const queryClient = useQueryClient();

  const reports = useQuery({
    queryKey: ["travel-expense-reports", profile?.id],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("travel_expense_reports")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) throw error;
      return data as TravelExpenseReport[];
    },
    enabled: !!profile?.id,
  });

  const getReportItems = (reportId: string) =>
    useQuery({
      queryKey: ["travel-expense-items", reportId],
      queryFn: async () => {
        const { data, error } = await supabase
          .from("travel_expense_items")
          .select("*")
          .eq("report_id", reportId)
          .order("date", { ascending: true });

        if (error) throw error;
        return data as TravelExpenseItem[];
      },
      enabled: !!reportId,
    });

  const createReport = useMutation({
    mutationFn: async (input: CreateTravelExpenseInput) => {
      if (!profile?.id || !profile?.company_id) throw new Error("Ikke innlogget");

      const { items, ...reportData } = input;

      // Calculate totals
      const mileageAmount = input.total_km * input.mileage_rate;
      const dietAmount = (input.diet_days || 0) * (input.diet_rate || 0);
      const accommodationAmount = (input.accommodation_days || 0) * (input.accommodation_rate || 0);
      const itemsTotal = items?.reduce((sum, i) => sum + i.amount, 0) || 0;
      const totalAmount = mileageAmount + (input.passenger_supplement || 0) + dietAmount + accommodationAmount + itemsTotal;

      const { data: report, error } = await supabase
        .from("travel_expense_reports")
        .insert({
          user_id: profile.id,
          company_id: profile.company_id,
          report_number: "", // Auto-generated by trigger
          purpose: reportData.purpose,
          destination: reportData.destination,
          departure_date: reportData.departure_date,
          return_date: reportData.return_date,
          departure_location: reportData.departure_location,
          total_km: reportData.total_km,
          mileage_rate: reportData.mileage_rate,
          passenger_supplement: reportData.passenger_supplement || 0,
          diet_days: reportData.diet_days || 0,
          diet_rate: reportData.diet_rate || 0,
          accommodation_days: reportData.accommodation_days || 0,
          accommodation_rate: reportData.accommodation_rate || 0,
          other_expenses_total: itemsTotal,
          total_amount: totalAmount,
          linked_trip_ids: reportData.linked_trip_ids || [],
          notes: reportData.notes,
          status: "draft",
        })
        .select()
        .single();

      if (error) throw error;

      // Upload items with receipts
      if (items && items.length > 0) {
        for (const item of items) {
          let receipt_path: string | null = null;

          if (item.receipt_file) {
            const fileExt = item.receipt_file.name.split(".").pop();
            const filePath = `${profile.id}/${report.id}/${crypto.randomUUID()}.${fileExt}`;
            const { error: uploadError } = await supabase.storage
              .from("driving-log-receipts")
              .upload(filePath, item.receipt_file);
            if (uploadError) throw uploadError;
            receipt_path = filePath;
          }

          const { error: itemError } = await supabase
            .from("travel_expense_items")
            .insert({
              report_id: report.id,
              category: item.category,
              description: item.description,
              date: item.date,
              amount: item.amount,
              receipt_path,
            });

          if (itemError) throw itemError;
        }
      }

      return report;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["travel-expense-reports"] });
      toast.success("Reiseregning opprettet");
    },
    onError: (error) => {
      toast.error("Kunne ikke opprette reiseregning: " + error.message);
    },
  });

  const submitReport = useMutation({
    mutationFn: async (reportId: string) => {
      const { data, error } = await supabase
        .from("travel_expense_reports")
        .update({
          status: "submitted",
          submitted_at: new Date().toISOString(),
        })
        .eq("id", reportId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["travel-expense-reports"] });
      toast.success("Reiseregning sendt til godkjenning");
    },
    onError: (error) => {
      toast.error("Kunne ikke sende reiseregning: " + error.message);
    },
  });

  const approveReport = useMutation({
    mutationFn: async (reportId: string) => {
      if (!profile?.id) throw new Error("Ikke innlogget");
      const approverName = `${profile.first_name || ""} ${profile.last_name || ""}`.trim();

      const { data, error } = await supabase
        .from("travel_expense_reports")
        .update({
          status: "approved",
          approved_by_id: profile.id,
          approved_by_name: approverName,
          approved_at: new Date().toISOString(),
        })
        .eq("id", reportId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["travel-expense-reports"] });
      toast.success("Reiseregning godkjent");
    },
    onError: (error) => {
      toast.error("Kunne ikke godkjenne: " + error.message);
    },
  });

  const rejectReport = useMutation({
    mutationFn: async ({ reportId, reason }: { reportId: string; reason: string }) => {
      const { data, error } = await supabase
        .from("travel_expense_reports")
        .update({
          status: "rejected",
          rejection_reason: reason,
        })
        .eq("id", reportId)
        .select()
        .single();

      if (error) throw error;
      return data;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["travel-expense-reports"] });
      toast.success("Reiseregning avvist");
    },
    onError: (error) => {
      toast.error("Kunne ikke avvise: " + error.message);
    },
  });

  const deleteReport = useMutation({
    mutationFn: async (reportId: string) => {
      const { error } = await supabase
        .from("travel_expense_reports")
        .delete()
        .eq("id", reportId);

      if (error) throw error;
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["travel-expense-reports"] });
      toast.success("Reiseregning slettet");
    },
    onError: (error) => {
      toast.error("Kunne ikke slette reiseregning: " + error.message);
    },
  });

  return {
    reports,
    getReportItems,
    createReport,
    submitReport,
    approveReport,
    rejectReport,
    deleteReport,
  };
}
