// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.108.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function currentProfile(ctx) {
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("profiles").select("id, user_id, company_id, first_name, last_name, email, role").eq("user_id", ctx.getUserId() ?? "").maybeSingle();
  if (error) throw new Error(error.message);
  if (!data) throw new Error("Fant ingen brukerprofil for denne kontoen.");
  return { supabase, profile: data };
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Hvem er jeg",
  description: "Returnerer den innloggede brukerens profil og tilh\xF8rende bedrift i Total-IK.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const { supabase, profile } = await currentProfile(ctx);
    const { data: company } = await supabase.from("companies").select("id, name, org_number").eq("id", profile.company_id).maybeSingle();
    const result = { profile, company };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-deviations.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_deviations_default = defineTool2({
  name: "list_deviations",
  title: "List avvik",
  description: "Henter avvik (deviations) for brukerens bedrift, med valgfritt filter p\xE5 status og antall.",
  inputSchema: {
    status: z.enum(["open", "in_progress", "resolved", "closed"]).optional().describe("Filtrer p\xE5 status."),
    limit: z.number().int().min(1).max(100).default(20).describe("Maks antall avvik.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const { supabase, profile } = await currentProfile(ctx);
    let query = supabase.from("deviations").select("id, deviation_number, title, category, priority, status, due_date, assignee_name, reporter_name, created_at").eq("company_id", profile.company_id).eq("is_deleted", false).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { deviations: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-deviation.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_deviation_default = defineTool3({
  name: "create_deviation",
  title: "Opprett avvik",
  description: "Registrerer et nytt avvik i Total-IK for brukerens bedrift. Avviksnummer genereres automatisk.",
  inputSchema: {
    title: z2.string().trim().min(3).describe("Kort tittel p\xE5 avviket."),
    description: z2.string().trim().optional().describe("Utfyllende beskrivelse."),
    category: z2.enum(["quality", "safety", "environment", "documentation", "other"]).default("other").describe("Kategori."),
    priority: z2.enum(["low", "medium", "high", "critical"]).default("medium").describe("Prioritet."),
    due_date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Frist p\xE5 formatet YYYY-MM-DD. Standard er 14 dager frem i tid.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, description, category, priority, due_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const { supabase, profile } = await currentProfile(ctx);
    const fallbackDue = /* @__PURE__ */ new Date();
    fallbackDue.setDate(fallbackDue.getDate() + 14);
    const pad = (n) => String(n).padStart(2, "0");
    const dueDate = due_date ?? `${fallbackDue.getFullYear()}-${pad(fallbackDue.getMonth() + 1)}-${pad(fallbackDue.getDate())}`;
    const reporterName = `${profile.first_name ?? ""} ${profile.last_name ?? ""}`.trim() || (profile.email ?? "Ukjent");
    const { data, error } = await supabase.from("deviations").insert({
      company_id: profile.company_id,
      deviation_number: null,
      title,
      description: description ?? null,
      category,
      priority,
      status: "open",
      due_date: dueDate,
      reporter_id: ctx.getUserId(),
      reporter_name: reporterName
    }).select("id, deviation_number, title, status, due_date").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Avvik opprettet: ${JSON.stringify(data)}` }],
      structuredContent: { deviation: data }
    };
  }
});

// src/lib/mcp/tools/list-projects.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_projects_default = defineTool4({
  name: "list_projects",
  title: "List byggeprosjekter",
  description: "Henter KS-byggeprosjekter for brukerens bedrift, med valgfritt statusfilter.",
  inputSchema: {
    status: z3.enum(["planned", "active", "handover", "warranty", "completed"]).optional().describe("Filtrer p\xE5 prosjektstatus."),
    limit: z3.number().int().min(1).max(100).default(20).describe("Maks antall prosjekter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const { supabase, profile } = await currentProfile(ctx);
    let query = supabase.from("ks_module2_projects").select("id, project_number, project_name, address, client_name, status, progress_percent, planned_start_date, planned_end_date").eq("company_id", profile.company_id).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-time-entries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_time_entries_default = defineTool5({
  name: "list_time_entries",
  title: "List timef\xF8ringer",
  description: "Henter den innloggede brukerens egne timef\xF8ringer i en valgfri datoperiode.",
  inputSchema: {
    from_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Fra-dato YYYY-MM-DD."),
    to_date: z4.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Til-dato YYYY-MM-DD."),
    limit: z4.number().int().min(1).max(200).default(50).describe("Maks antall linjer.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from_date, to_date, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Ikke innlogget" }], isError: true };
    }
    const { supabase } = await currentProfile(ctx);
    let query = supabase.from("time_entries").select("id, entry_date, hours, hour_type, start_time, end_time, project_name, customer_name, description, status").eq("user_id", ctx.getUserId() ?? "").order("entry_date", { ascending: false }).limit(limit ?? 50);
    if (from_date) query = query.gte("entry_date", from_date);
    if (to_date) query = query.lte("entry_date", to_date);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const total = (data ?? []).reduce((sum, r) => sum + (Number(r.hours) || 0), 0);
    return {
      content: [{ type: "text", text: JSON.stringify({ total_hours: total, entries: data ?? [] }, null, 2) }],
      structuredContent: { total_hours: total, entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sffkcqclfiffnpxorodd";
var mcp_default = defineMcp({
  name: "totalik-no",
  title: "Totalik.no",
  version: "0.1.0",
  instructions: "Verkt\xF8y for Total-IK (HMS, internkontroll og kvalitetssikring). Bruk `whoami` for \xE5 se brukerens bedrift, `list_deviations`/`create_deviation` for avvik, `list_projects` for KS-byggeprosjekter og `list_time_entries` for egne timef\xF8ringer. Alle data er begrenset til den innloggede brukerens bedrift.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_deviations_default, create_deviation_default, list_projects_default, list_time_entries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
