-- Fix: Storage RLS Policies Allow Cross-Company Photo Access
-- The buckets are already private, but SELECT policies are overly permissive
-- Since the application uses signed URLs for all photo access, we can safely drop the broad SELECT policies

-- Drop overly permissive SELECT policies for avvik photos
DROP POLICY IF EXISTS "Users can view avvik photos" ON storage.objects;

-- Drop overly permissive SELECT policies for checklist photos
DROP POLICY IF EXISTS "Users can view checklist photos" ON storage.objects;

-- Also check and fix inspection-photos bucket if it has similar issues
DROP POLICY IF EXISTS "Users can view inspection photos" ON storage.objects;

-- The application already uses createSignedUrl() which bypasses RLS policies
-- File access is now only possible via time-limited signed URLs generated by the application
-- This ensures users can only access photos for projects they have access to