-- Insert additional system templates based on the uploaded documents
INSERT INTO public.hms_vernerunde_templates (template_name, description, checkpoints, is_system_template, is_active) VALUES
(
  'Arbeidsplasser og personalrom',
  'Sjekkliste for orden, renhold, arbeidsplasser, belysning, klima og personalrom',
  '[
    {"id": "1", "category": "Orden og renhold", "checkpoint": "Er renholdet tilfredsstillende?", "help_text": null},
    {"id": "2", "category": "Orden og renhold", "checkpoint": "Er det faste renholdsrutiner, og følges disse?", "help_text": null},
    {"id": "3", "category": "Orden og renhold", "checkpoint": "Utføres det regelmessig hovedrengjøring?", "help_text": null},
    {"id": "4", "category": "Orden og renhold", "checkpoint": "Er det faste rydderutiner?", "help_text": null},
    {"id": "5", "category": "Orden og renhold", "checkpoint": "Forekommer det klager fra arbeidstakere over slike problemer?", "help_text": null},
    {"id": "6", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er arbeidsplassen tilrettelagt slik at det kan sysselsettes arbeidstakere av begge kjønn?", "help_text": null},
    {"id": "7", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er det adskilte garderober og toaletter for kvinner og menn?", "help_text": null},
    {"id": "8", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er atkomstveier og garderober/toaletter tilrettelagt for arbeidstakere med funksjonshemning?", "help_text": null},
    {"id": "9", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er arbeidslokalene og atkomsten til lokalene utformet og innredet med sikte på virksomheten?", "help_text": null},
    {"id": "10", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er atkomstveiene trygge (gående og kjøretøy atskilt)?", "help_text": null},
    {"id": "11", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er rømningsveiene godt nok merket?", "help_text": null},
    {"id": "12", "category": "Arbeidsplasser og arbeidslokaler", "checkpoint": "Er arbeidslokalene og andre fellesrom røykfrie?", "help_text": null},
    {"id": "13", "category": "Belysning", "checkpoint": "Er det mulighet for dagslys og utsyn på de enkelte arbeidsplassene?", "help_text": null},
    {"id": "14", "category": "Belysning", "checkpoint": "Er både allmennbelysningen og plassbelysningen tilfredsstillende?", "help_text": null},
    {"id": "15", "category": "Belysning", "checkpoint": "Har det nylig vært utført lysmålinger?", "help_text": null},
    {"id": "16", "category": "Belysning", "checkpoint": "Finnes det rutiner for renhold av armatur og skifting av lysrør?", "help_text": null},
    {"id": "17", "category": "Klima og luftkvalitet", "checkpoint": "Er allmennventilasjonen god nok?", "help_text": null},
    {"id": "18", "category": "Klima og luftkvalitet", "checkpoint": "Har den driftsansvarlige fått tilstrekkelig opplæring i driften av ventilasjonsanlegget?", "help_text": null},
    {"id": "19", "category": "Klima og luftkvalitet", "checkpoint": "Er det foretatt målinger siden forrige runde?", "help_text": null},
    {"id": "20", "category": "Klima og luftkvalitet", "checkpoint": "Finnes det rutiner for renhold, kontroll av reimer, filterskift osv.?", "help_text": null},
    {"id": "21", "category": "Klima og luftkvalitet", "checkpoint": "Blir kanaler sjekket for støv og andre forurensninger?", "help_text": null},
    {"id": "22", "category": "Klima og luftkvalitet", "checkpoint": "Er luftinntaket rent og hensiktsmessig plassert?", "help_text": null},
    {"id": "23", "category": "Klima og luftkvalitet", "checkpoint": "Oppleves temperaturen som tilfredsstillende?", "help_text": null},
    {"id": "24", "category": "Klima og luftkvalitet", "checkpoint": "Er det trekk, og hvor kommer den i så fall fra?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Elektriske installasjoner',
  'Egenkontroll av elektriske installasjoner og utstyr',
  '[
    {"id": "1", "category": "Generelle forhold", "checkpoint": "Finnes det ajourført dokumentasjon for anlegget?", "help_text": null},
    {"id": "2", "category": "Generelle forhold", "checkpoint": "Føres det journaler over driftstekniske forstyrrelser på installasjoner og utstyr?", "help_text": null},
    {"id": "3", "category": "Generelle forhold", "checkpoint": "Har det siden forrige kontroll vært noe unormalt ved installasjoner og utstyr?", "help_text": null},
    {"id": "4", "category": "Generelle forhold", "checkpoint": "Er det synlige feil/mangler eller skader på installasjoner og utstyr?", "help_text": null},
    {"id": "5", "category": "Generelle forhold", "checkpoint": "Finnes det bruks- og monteringsanvisninger for installasjoner og utstyr?", "help_text": null},
    {"id": "6", "category": "Generelle forhold", "checkpoint": "Føres det avviksmeldinger dersom det oppstår skader på installasjoner og utstyr?", "help_text": null},
    {"id": "7", "category": "Inntak/sikringsskap", "checkpoint": "Er sikringene, brytere eller vern unormalt varme?", "help_text": null},
    {"id": "8", "category": "Inntak/sikringsskap", "checkpoint": "Er sikringene godt tilskrudd? (ikke aktuelt ved automatsikring)", "help_text": null},
    {"id": "9", "category": "Inntak/sikringsskap", "checkpoint": "Er det synlig skade på kabelen?", "help_text": null},
    {"id": "10", "category": "Inntak/sikringsskap", "checkpoint": "Er kursoversikten(e) ajourført?", "help_text": null},
    {"id": "11", "category": "Inntak/sikringsskap", "checkpoint": "Er sikringer og brytere merket i henhold til kursoversikt?", "help_text": null},
    {"id": "12", "category": "Inntak/sikringsskap", "checkpoint": "Fungerer testknapp på jordfeilbryter og -varsler?", "help_text": null},
    {"id": "13", "category": "Inntak/sikringsskap", "checkpoint": "Er det ryddig og rent i tavlerom/sikringsskap?", "help_text": null},
    {"id": "14", "category": "Inntak/sikringsskap", "checkpoint": "Er hovedtavle/sikringsskap lukket og låst?", "help_text": null},
    {"id": "15", "category": "Inntak/sikringsskap", "checkpoint": "Er hovedtavlerom/sikringsskap forskriftsmessig branntettet?", "help_text": null},
    {"id": "16", "category": "Inntak/sikringsskap", "checkpoint": "Kobler noen av sikringene ofte ut?", "help_text": null},
    {"id": "17", "category": "Installasjoner", "checkpoint": "Er det utstrakt bruk av skjøteledninger?", "help_text": null},
    {"id": "18", "category": "Installasjoner", "checkpoint": "Er ledninger forlagt slik at de ikke kan bli påført skader under normale forhold?", "help_text": null},
    {"id": "19", "category": "Installasjoner", "checkpoint": "Er ledninger, koblingsbokser og stikkontakter uten skader?", "help_text": null},
    {"id": "20", "category": "Installasjoner", "checkpoint": "Er ledninger, koblingsbokser og stikkontakter forsvarlig festet til underlaget?", "help_text": null},
    {"id": "21", "category": "Installasjoner", "checkpoint": "Er ledninger, koblingsbokser og stikkontakter dimensjonert for bruksområdet?", "help_text": null},
    {"id": "22", "category": "Installasjoner", "checkpoint": "Er det varmegang i kontakter og/eller koblingsbokser?", "help_text": null},
    {"id": "23", "category": "Materiell/utstyr", "checkpoint": "Gjennomføres det systematisk service og vedlikehold av løst elektrisk utstyr?", "help_text": null},
    {"id": "24", "category": "Materiell/utstyr", "checkpoint": "Følges bruksanvisninger for elektrisk utstyr?", "help_text": null},
    {"id": "25", "category": "Materiell/utstyr", "checkpoint": "Er det elektriske utstyret uten skader?", "help_text": null},
    {"id": "26", "category": "Materiell/utstyr", "checkpoint": "Skiftes tennere til lysstoffrør samtidig som lysstoffrørene skiftes ut?", "help_text": null},
    {"id": "27", "category": "Materiell/utstyr", "checkpoint": "Finnes det sikkerhetsrutiner for bruk av kaffetraktere (f.eks. montert tidsur)?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Kjemikalier og forurensning',
  'Sjekkliste for kjemiske stoffer, biologiske faktorer og luftforurensninger',
  '[
    {"id": "1", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Benyttes det kjemiske stoffer?", "help_text": null},
    {"id": "2", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Har disse tilfredsstillende norske sikkerhetsdata?", "help_text": null},
    {"id": "3", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er sikkerhetsdatabladene samlet i et stoffkartotek?", "help_text": null},
    {"id": "4", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er stoffkartoteket tilgjengelig for brukerne?", "help_text": null},
    {"id": "5", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er brukerne kjent med innholdet i sikkerhetsdatabladene?", "help_text": null},
    {"id": "6", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Brukes det kun originalemballasje?", "help_text": null},
    {"id": "7", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er beholdere og emballasje tydelig merket med stoffets navn og advarsel på norsk?", "help_text": null},
    {"id": "8", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Benyttes det riktig verneutstyr?", "help_text": null},
    {"id": "9", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Finnes det øyenskylleutstyr på steder hvor man håndterer kjemikalier?", "help_text": null},
    {"id": "10", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Kreves det for noen av kjemikaliene at spesielle arbeidsinstrukser skal utarbeides og følges?", "help_text": null},
    {"id": "11", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er innkjøpsrutinene tilfredsstillende?", "help_text": null},
    {"id": "12", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Oppbevares og transporteres kjemikalier tilfredsstillende?", "help_text": null},
    {"id": "13", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Kan noen stoffer erstattes med mindre helsefarlige produkter?", "help_text": null},
    {"id": "14", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Kan antall stoffer reduseres?", "help_text": null},
    {"id": "15", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Finnes det gode rutiner for renhold og avfallshåndtering?", "help_text": null},
    {"id": "16", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Kan arbeidstakerne bli eksponert for biologiske faktorer i forbindelse med arbeidet?", "help_text": null},
    {"id": "17", "category": "Kjemiske stoffer og biologiske faktorer", "checkpoint": "Er det foretatt en risikovurdering av kjemiske og biologiske faktorer?", "help_text": null},
    {"id": "18", "category": "Luftforurensinger", "checkpoint": "Arbeides det med stoffer som avgir støv eller andre luftforurensinger?", "help_text": null},
    {"id": "19", "category": "Luftforurensinger", "checkpoint": "Foregår det forurensende arbeidsprosesser?", "help_text": null},
    {"id": "20", "category": "Luftforurensinger", "checkpoint": "Er det foretatt en vurdering og evt. måling av forurensningene?", "help_text": null},
    {"id": "21", "category": "Luftforurensinger", "checkpoint": "Er ventilasjon tilfredsstillende? (almennventilasjon og evt. punktavsug)", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Maskiner og utstyr - Sikkerhet og vern',
  'Sjekkliste for sikkerhet ved maskiner og personlig verneutstyr',
  '[
    {"id": "1", "category": "Sikkerhet", "checkpoint": "Brukes det prestasjonslønn for arbeid hvor dette kan ha vesentlig betydning for sikkerheten?", "help_text": null},
    {"id": "2", "category": "Sikkerhet", "checkpoint": "Forekommer det farlige arbeidssituasjoner?", "help_text": null},
    {"id": "3", "category": "Sikkerhet", "checkpoint": "Har virksomheten foretatt en risikovurdering mht. farlige arbeidsforhold?", "help_text": null},
    {"id": "4", "category": "Sikkerhet", "checkpoint": "Finnes det sikkerhetsprosedyrer eller arbeidsinstrukser, og følges disse?", "help_text": null},
    {"id": "5", "category": "Sikkerhet", "checkpoint": "Er maskiner og utstyr forsvarlig sikret?", "help_text": null},
    {"id": "6", "category": "Sikkerhet", "checkpoint": "Føres det regelmessig kontroll med sikkerhetsutstyret?", "help_text": null},
    {"id": "7", "category": "Sikkerhet", "checkpoint": "Har operatørene fått nødvendig opplæring?", "help_text": null},
    {"id": "8", "category": "Sikkerhet", "checkpoint": "Blir arbeidstakerne informert om skaderisikoen?", "help_text": null},
    {"id": "9", "category": "Sikkerhet", "checkpoint": "Er det farlige forhold i bedriften som krever sikkerhetsskilting og signalgivning?", "help_text": null},
    {"id": "10", "category": "Sikkerhet", "checkpoint": "Får arbeidstakerne informasjon, opplæring og instruksjon om sikkerhetsskilting?", "help_text": null},
    {"id": "11", "category": "Sikkerhet", "checkpoint": "Er førstehjelpsutstyr plassert lett tilgjengelig for alle arbeidstakere?", "help_text": null},
    {"id": "12", "category": "Sikkerhet", "checkpoint": "Er det foretatt en vurdering av utendørsarbeidsplassene (vær, trafikk, lysforhold, fallrisiko)?", "help_text": null},
    {"id": "13", "category": "Personlig verneutstyr", "checkpoint": "Er nødvendig og riktig tilpasset verneutstyr tilgjengelig?", "help_text": null},
    {"id": "14", "category": "Personlig verneutstyr", "checkpoint": "Oppbevares og vedlikeholdes utstyret på forsvarlig måte?", "help_text": null},
    {"id": "15", "category": "Personlig verneutstyr", "checkpoint": "Er verneutstyret CE-merket, og har det norsk brukerveiledning?", "help_text": null},
    {"id": "16", "category": "Personlig verneutstyr", "checkpoint": "Er det gitt opplæring i bruk av verneutstyret?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Tilrettelegging av arbeidet',
  'Sjekkliste for ergonomi og organisatoriske/psykososiale forhold',
  '[
    {"id": "1", "category": "Ergonomi", "checkpoint": "Forekommer det arbeid som er i rød sone til Arbeidstilsynets vurderingsmodell \"tungt og ensformig arbeid\"?", "help_text": null},
    {"id": "2", "category": "Ergonomi", "checkpoint": "Kan løfteutstyr eller andre hjelpemidler benyttes?", "help_text": null},
    {"id": "3", "category": "Ergonomi", "checkpoint": "Finnes det variasjonsmuligheter, for eksempel ved jobbrotasjon eller pauser?", "help_text": null},
    {"id": "4", "category": "Ergonomi", "checkpoint": "Kan arbeidsplassen tilrettelegges for å redusere uhensiktsmessige arbeidsstillinger?", "help_text": null},
    {"id": "5", "category": "Ergonomi", "checkpoint": "Er dataarbeidsplassen riktig tilrettelagt, og gis det mulighet til regelmessige pauser fra skjermarbeidet?", "help_text": null},
    {"id": "6", "category": "Ergonomi", "checkpoint": "Er dataarbeidsplassene tilpasset for arbeidets art og den enkelte arbeidstaker?", "help_text": null},
    {"id": "7", "category": "Ergonomi", "checkpoint": "Har de ansatte fått opplæring i god arbeidsteknikk?", "help_text": null},
    {"id": "8", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Finnes det regler for hvordan man griper inn ved trakassering, mobbing eller annen utilbørlig opptreden?", "help_text": null},
    {"id": "9", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Er arbeidet tilrettelagt slik at den ansattes verdighet ivaretas?", "help_text": null},
    {"id": "10", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Gir arbeidet mulighet for variasjon, læring og utvikling?", "help_text": null},
    {"id": "11", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Gir arbeidet mulighet for kontakt med andre, kontroll over egen arbeidssituasjon og selvstendige avgjørelser?", "help_text": null},
    {"id": "12", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Finnes det arbeidsinstrukser?", "help_text": null},
    {"id": "13", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Holdes arbeidstakerne orientert om nye planleggings- og styringssystemer?", "help_text": null},
    {"id": "14", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Er kommunikasjonslinjene klare og gjenkjennelige for alle?", "help_text": null},
    {"id": "15", "category": "Organisatoriske og psykososiale forhold", "checkpoint": "Finnes det arenaer der de ansatte kan gi og få tilbakemeldinger?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Vernetjenesten',
  'Sjekkliste for verneombud, AMU og bedriftshelsetjeneste',
  '[
    {"id": "1", "category": "Verneombud", "checkpoint": "Har virksomheten valgt verneombud? (Aml. § 6-1)", "help_text": null},
    {"id": "2", "category": "Verneombud", "checkpoint": "Får verneombudet lovfestet opplæring? (Aml. § 6-5 (1))", "help_text": null},
    {"id": "3", "category": "Verneombud", "checkpoint": "Tilrettelegges arbeidsforholdene slik at verneombudet får mulighet til å fylle vervet sitt?", "help_text": null},
    {"id": "4", "category": "Verneombud", "checkpoint": "Deltar verneombudet i kartleggingsarbeid og ved utarbeidelse av handlingsplaner?", "help_text": null},
    {"id": "5", "category": "AMU", "checkpoint": "Hvis virksomheten har 50 ansatte eller flere, er arbeidsmiljøutvalg (AMU) opprettet?", "help_text": null},
    {"id": "6", "category": "AMU", "checkpoint": "Har AMU faste møter?", "help_text": null},
    {"id": "7", "category": "AMU", "checkpoint": "Har AMU avgitt sin årlige rapport til virksomhetens styrende organer?", "help_text": null},
    {"id": "8", "category": "AMU", "checkpoint": "Har AMU-medlemmene gjennomgått grunnopplæring i helse-, miljø- og sikkerhetsarbeid?", "help_text": null},
    {"id": "9", "category": "AMU", "checkpoint": "Behandler AMU saker i henhold til myndighetenes krav?", "help_text": null},
    {"id": "10", "category": "AMU", "checkpoint": "Er oversikt over verneombud og medlemmer av AMU kunngjort ved oppslag på arbeidsplassen?", "help_text": null},
    {"id": "11", "category": "Bedriftshelsetjeneste", "checkpoint": "Tilhører bedriften en bransjegruppe som er pålagt å knytte til seg bedriftshelsetjeneste?", "help_text": null},
    {"id": "12", "category": "Bedriftshelsetjeneste", "checkpoint": "Er det utarbeidet periodevise planer for bedriftshelsetjenesten i virksomheten?", "help_text": null},
    {"id": "13", "category": "Bedriftshelsetjeneste", "checkpoint": "Er det utarbeidet årsrapport fra bedriftshelsetjenesten?", "help_text": null},
    {"id": "14", "category": "Bedriftshelsetjeneste", "checkpoint": "Utarbeider bedriftshelsetjenesten rapporter som beskriver helsefarlige arbeidsforhold?", "help_text": null},
    {"id": "15", "category": "Bedriftshelsetjeneste", "checkpoint": "Blir de forhold som rapporteres, fulgt opp av bedriften?", "help_text": null},
    {"id": "16", "category": "Bedriftshelsetjeneste", "checkpoint": "Deltar det representanter fra bedriftshelsetjenesten på AMU-møter eller andre samarbeidsmøter?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Ytre miljø',
  'Sjekkliste for avfall, farlig avfall, utslipp og støy til omgivelsene',
  '[
    {"id": "1", "category": "Avfall", "checkpoint": "Sorteres avfallet i virksomheten?", "help_text": null},
    {"id": "2", "category": "Avfall", "checkpoint": "Sorteres papir?", "help_text": null},
    {"id": "3", "category": "Avfall", "checkpoint": "Sorteres brunt papir?", "help_text": null},
    {"id": "4", "category": "Avfall", "checkpoint": "Sorteres plast?", "help_text": null},
    {"id": "5", "category": "Avfall", "checkpoint": "Sorteres metaller?", "help_text": null},
    {"id": "6", "category": "Avfall", "checkpoint": "Sorteres glass?", "help_text": null},
    {"id": "7", "category": "Avfall", "checkpoint": "Sorteres organisk materiale?", "help_text": null},
    {"id": "8", "category": "Farlig avfall", "checkpoint": "Har bedriften rutiner for håndtering av farlig avfall?", "help_text": null},
    {"id": "9", "category": "Utslipp til luft", "checkpoint": "Forekommer det feil ved rør/pipe?", "help_text": null},
    {"id": "10", "category": "Utslipp til luft", "checkpoint": "Er det mangler på filter eller renseanordning?", "help_text": null},
    {"id": "11", "category": "Utslipp til luft", "checkpoint": "Er det tilfredsstillende vedlikeholdsrutiner?", "help_text": null},
    {"id": "12", "category": "Utslipp til vann", "checkpoint": "Forekommer det feil eller ureglementert bruk av avløpssluk?", "help_text": null},
    {"id": "13", "category": "Utslipp til vann", "checkpoint": "Er det lekkasjer på rørledningsnett?", "help_text": null},
    {"id": "14", "category": "Utslipp til vann", "checkpoint": "Er renseanordningene intakte og vedlikeholdte?", "help_text": null},
    {"id": "15", "category": "Støy til omgivelsene", "checkpoint": "Gir ventilasjonsanlegg, luftkjølte kondensatorer sjenerende støy?", "help_text": null}
  ]'::jsonb,
  true,
  true
),
(
  'Årlig gjennomgang av HMS-system',
  'Sjekkliste for årlig revisjon av HMS-systemet',
  '[
    {"id": "1", "category": "HMS-system gjennomgang", "checkpoint": "Er bedriftens konkrete målsetting for HMS-arbeidet fortsatt aktuell?", "help_text": null},
    {"id": "2", "category": "HMS-system gjennomgang", "checkpoint": "Er handlingsplanen fra foregående år fulgt opp?", "help_text": null},
    {"id": "3", "category": "HMS-system gjennomgang", "checkpoint": "Er meldinger om avvik og feil blitt behandlet i henhold til rutine?", "help_text": null},
    {"id": "4", "category": "HMS-system gjennomgang", "checkpoint": "Er det endringer i lover og forskrifter som påvirker oss?", "help_text": null},
    {"id": "5", "category": "HMS-system gjennomgang", "checkpoint": "Er systemet og rutinene godt nok kjent av alle i bedriften?", "help_text": null},
    {"id": "6", "category": "HMS-system gjennomgang", "checkpoint": "Er det noen endringer i arbeidsoppgaver eller arbeidsutstyr som gjør at rutinene bør endres?", "help_text": null},
    {"id": "7", "category": "HMS-system gjennomgang", "checkpoint": "Er det noen nye arbeidsoppgaver eller arbeidsutstyr som ikke er kartlagt og risikovurdert?", "help_text": null},
    {"id": "8", "category": "HMS-system gjennomgang", "checkpoint": "Har noen nye ansatte eller faste ansatte behov for mer eller ytterligere opplæring?", "help_text": null},
    {"id": "9", "category": "HMS-system gjennomgang", "checkpoint": "Er organisasjonskartet oppdatert?", "help_text": null},
    {"id": "10", "category": "HMS-system gjennomgang", "checkpoint": "Har de ansatte mulighet å påvirke i det systematisk HMS-arbeidet? (daglig drift, personalmøte, medarbeidersamtale, vernerunder)", "help_text": null}
  ]'::jsonb,
  true,
  true
);